config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users,
             controllers: {
                omniauth_callbacks: 'users/omniauth_callbacks',
                registrations: 'users/registrations'
              }

  resource :general, only: [:show, :create, :update]
  resource :profile, only: [:show, :create, :update]
  resource :motivation, only: [:show, :create, :update]
  resource :presentation, only: [:show, :create, :update]
  resources :educations
  resources :academics, only: [:index]
  resources :conferences, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :others, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :publications, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :trainings, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :works
  resource :language, only: [:show, :create, :update]

  post '/submit', to: 'submit#submit', as: :submit

  resources :reviews, only: [:index, :show, :create, :emails] do
    collection do
      get :emails
    end

    scope module: :review_process do
      resource :general, only: :show
      resource :profile, only: :show
      resource :motivation, only: [:show, :update]
      resource :presentation, only: [:show, :update]
      resource :educations, only: [:show, :update]
      resource :academics, only: [:show, :update]
      resource :works, only: [:show, :update]
      resource :language, only: [:show, :update]
    end
  end

  resources :users, only: [:index, :show] do
    scope module: :user_previews do
      resource :general, only: :show
      resource :profile, only: :show
      resource :motivation, only: :show
      resource :presentation, only: :show
      resource :educations, only: :show
      resource :academics, only: :show
      resource :works, only: :show
      resource :language, only: :show
      resource :overview, only: :show
    end
  end

  resource :ranking, only: :show
  resource :report, only: :show
end

app/models/training.rb
class Training < ActiveRecord::Base
  include Countryable

  validates :title,
            presence: true

  validates :institution,
            presence: true

  validates :start_date,
              presence: true,
              date: true

  validates :end_date,
            presence: true,
            date: { after_or_equal_to: :start_date }

  belongs_to :user,
             required: true
end

app/controllers/trainings_controller.rb
class TrainingsController < AjaxController
  load_and_authorize_resource
  before_action :set_item

  private

  def set_item
    @item = @training
  end

  def training_params
    params.require(:training).
      permit(:title, :institution, :country, :start_date, :end_date)
  end

  alias_method :item_params, :training_params

  def count_id
    'academic-count'
  end

  def count
    @count ||= current_user.academic_count
  end
end

app/views/trainings/_form.html.haml
= simple_form_for @training,
                  html: { class: 'form-horizontal', role: 'form', id: 'modal_form' },
                  remote: true,
                  wrapper: :horizontal_form do |f|
  = f.input :title
  = f.input :institution
  = f.input :country
  = f.input :date, as: :date_interval, required: true

app/views/trainings/_index.html.haml
%h4= t('training.title')
%p.help-block= t('help.training')
- if can?(:create, current_user.trainings.build)
  = link_to new_training_path,
            class: "btn btn-success",
            data: { toggle: "modal", target: "#ajax-modal" },
            remote: true do
    = icon('plus', t('training.new'))

%ul.well-list#trainings-list
  - current_user.trainings.each do |item|
    - unless item.new_record?
      = render('trainings/item', item: item)

app/views/trainings/_item.html.haml
%li.clearfix(id="training-#{item.id}")
  .left
    = link_to_if can?(:edit, item), "#{item.title},", [:edit, item], title: item.title, remote: true do
      = link_to "#{item.title},", item, remote: true
    %small.light
      #{item.institution},
      -unless item.country.blank?
        #{item.country_name},
      from #{item.start_date} to #{item.end_date}.
  - if can?(:destroy, item)
    .pull-right
      =link_to item, remote: true,
                     method: :delete,
                     class: 'delete',
                     data: { confirm: t('training.destroy_confirmation') } do
        = icon('times')

app/views/trainings/_show.html.haml
%table.table.table-hover.table-bordered.show-table
  %tbody
    %tr
      %td= t('simple_form.labels.training.title')
      %td= @training.title
    %tr
      %td= t('simple_form.labels.training.institution')
      %td= @training.institution
    %tr
      %td= t('simple_form.labels.training.country')
      %td= @training.country_name
    %tr
      %td= t('simple_form.labels.training.date')
      %td #{@training.start_date} - #{@training.end_date}