config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users,
             controllers: {
                omniauth_callbacks: 'users/omniauth_callbacks',
                registrations: 'users/registrations'
              }

  resource :general, only: [:show, :create, :update]
  resource :profile, only: [:show, :create, :update]
  resource :motivation, only: [:show, :create, :update]
  resource :presentation, only: [:show, :create, :update]
  resources :educations
  resources :academics, only: [:index]
  resources :conferences, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :others, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :publications, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :trainings, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :works
  resource :language, only: [:show, :create, :update]

  post '/submit', to: 'submit#submit', as: :submit

  resources :reviews, only: [:index, :show, :create, :emails] do
    collection do
      get :emails
    end

    scope module: :review_process do
      resource :general, only: :show
      resource :profile, only: :show
      resource :motivation, only: [:show, :update]
      resource :presentation, only: [:show, :update]
      resource :educations, only: [:show, :update]
      resource :academics, only: [:show, :update]
      resource :works, only: [:show, :update]
      resource :language, only: [:show, :update]
    end
  end

  resources :users, only: [:index, :show] do
    scope module: :user_previews do
      resource :general, only: :show
      resource :profile, only: :show
      resource :motivation, only: :show
      resource :presentation, only: :show
      resource :educations, only: :show
      resource :academics, only: :show
      resource :works, only: :show
      resource :language, only: :show
      resource :overview, only: :show
    end
  end

  resource :ranking, only: :show
  resource :report, only: :show
end

app/models/education.rb
class Education < ActiveRecord::Base
  extend Enumerize

  EDUCATION_TYPES = %w(ba ma phd)

  validates :education_type,
            presence: true,
            inclusion: { in:  EDUCATION_TYPES }

  validates :start_date,
            presence: true,
            date: true

  validates :end_date,
            presence: true,
            date: { after: :start_date }

  validates :university_name,
            presence: true

  validates :program_name,
            presence: true

  validates :country,
            presence: true

  validates :user,
            presence: true

  belongs_to :user

  enumerize :education_type, in: EDUCATION_TYPES

  def title
    "#{education_type_text} #{program_name}"
  end
end

app/controllers/educations_controller.rb
class EducationsController < AjaxController
  load_and_authorize_resource
  before_action :set_item, except: [:index]

  def index
    @educations = @educations.order(:start_date, :end_date)
  end

  private

  def set_item
    @item = @education
  end

  def education_params
    params.require(:education).
      permit(:program_name, :university_name,
             :education_type, :start_date, :end_date, :country)
  end

  alias_method :item_params, :education_params

  def count_id
    'education-count'
  end

  def count
    @count ||= current_user.educations.count
  end

  def count_class
    'badge-success' if count > 0
  end

  def application_state
    if current_user.application_ready?
      'application_ready'
    else
      'application_not_ready'
    end
  end
end

app/controllers/review_process/educations_controller.rb
module ReviewProcess
  class EducationsController < ReviewProcess::ApplicationController
    def show
      @educations = @review.educations
    end

    private

    def update_params
      params.require(:review).permit(:education_score)
    end
  end
end

app/controllers/user_previews/educations_controller.rb
module UserPreviews
  class EducationsController < UserPreviews::ApplicationController
    def show
      @educations = @user.educations
    end
  end
end

app/views/educations/_form.html.haml
= simple_form_for @education,
                  html: { class: 'form-horizontal', role: 'form', id: 'modal_form' },
                  remote: true,
                  wrapper: :horizontal_form do |f|
  = f.input :education_type
  = f.input :program_name, as: :text, input_html: { rows: 3 }
  = f.input :university_name
  = f.input :country, as: :string
  = f.input :date, as: :date_interval, required: true

app/views/educations/_item.html.haml
%li.clearfix(id="education-#{item.id}")
  .left
    = link_to_if can?(:edit, item), item.title, [:edit, item], title: item.title, remote: true do
      = link_to item.title, item, remote: true
    %small.light
      from #{item.start_date} to #{item.end_date}, #{item.university_name}, #{item.country}

  - if can?(:destroy, item)
    .pull-right
      =link_to item, remote: true, method: :delete, class: 'delete', data: { confirm: t('education.destroy_confirmation') } do
        = icon('times')

app/views/educations/_show.html.haml
%table.table.table-hover.table-bordered.show-table
  %tbody
    %tr
      %td= t('simple_form.labels.education.education_type')
      %td= @education.education_type_text
    %tr
      %td= t('simple_form.labels.education.program_name')
      %td= @education.program_name
    %tr
      %td= t('simple_form.labels.education.university_name')
      %td= @education.university_name
    %tr
      %td= t('simple_form.labels.education.country')
      %td= @education.country
    %tr
      %td= t('simple_form.labels.education.date')
      %td #{@education.start_date} - #{@education.end_date}

app/views/educations/index.html.haml
%h3= t('education.title')
%hr

%p.help-block= t('help.education')
- if can?(:new, current_user.educations.build)
  = link_to new_education_path,
            class: "btn btn-success",
            data: { toggle: "modal", target: "#ajax-modal" },
            remote: true do
    = icon('plus', t('education.new'))

%ul.well-list#educations-list
  - @educations.each do |item|
    - unless item.new_record?
      = render('item', item: item)